ALTER TABLE reviews
ADD COLUMN IF NOT EXISTS testimonial_tag VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS testimonial_role VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS testimonial_avatar_bg TEXT NOT NULL DEFAULT '';
