[build]
  publish = "dist"
  command = "npm run build"

# Force HTTPS
[[redirects]]
  from = "http://a1frenchclasses.ca/*"
  to = "https://a1frenchclasses.ca/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.a1frenchclasses.ca/*"
  to = "https://a1frenchclasses.ca/:splat"
  status = 301
  force = true

# SPA catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "VITE_GOOGLE_CLIENT_ID"

[context.sandbox.environment]
  VITE_ENV = "sandbox"
  VITE_API_URL_SANDBOX = "https://sandbox-api.a1frenchclasses.ca"